version: '3'

services:
  redis:
    image: redis:7.4.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  postgres:
    image: postgres:16.1-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nestapp
      POSTGRES_PASSWORD: nestapp
      POSTGRES_DB: nestapp
    restart: always

  nestjs-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-api
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.env
    restart: always

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80'       # HTTP
      - '81:81'       # Panel admina
      - '443:443'     # HTTPS
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - nestjs-api
