version: '3'
services:
  redis:
    image: redis:7.4.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  postgres:
    image: postgres:16.1-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nestapp
      POSTGRES_PASSWORD: nestapp
      POSTGRES_DB: nestapp
    restart: always
